import Navbar from '@/Components/Navbar/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/Components/Footer/Footer';
import { ThemeProvider } from '@/lib/ThemeContext/ThemeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'HEXASHOP',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen `}>
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
